-- phpMyAdmin SQL Dump
-- version 5.0.2
-- https://www.phpmyadmin.net/
--
-- Host: localhost
-- Generation Time: Jan 20, 2021 at 01:17 PM
-- Server version: 10.4.14-MariaDB
-- PHP Version: 7.4.10

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `CSV_DB 6`
--

-- --------------------------------------------------------

--
-- Table structure for table `test`
--

CREATE TABLE `test` (
  `Name` varchar(21) DEFAULT NULL,
  `Symbol` varchar(6) DEFAULT NULL,
  `Atomicnumber` varchar(13) DEFAULT NULL,
  `Atomicmass` varchar(11) DEFAULT NULL,
  `Group` varchar(21) DEFAULT NULL,
  `OxidationStates` varchar(13) DEFAULT NULL,
  `property1` varchar(101) DEFAULT NULL,
  `property2` varchar(131) DEFAULT NULL,
  `property3` varchar(153) DEFAULT NULL,
  `wrong1` varchar(145) DEFAULT NULL,
  `wrong2` varchar(131) DEFAULT NULL,
  `wrong3` varchar(131) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Dumping data for table `test`
--

INSERT INTO `test` (`Name`, `Symbol`, `Atomicnumber`, `Atomicmass`, `Group`, `OxidationStates`, `property1`, `property2`, `property3`, `wrong1`, `wrong2`, `wrong3`) VALUES
('Chlorine', 'Cl', '17', '35.453', 'Halogen', 'Gas', 'corrodes nearly every metal and is toxic for every creature', 'part of the very common plastic PVC.', 'Has the form of a diatomic green gas', 'Most stars, including our Sun, generate energy by fusioning this to helium', 'lightest and simplest element and, with a ratio of 80%, is the main ingredient of the visible universe', 'contains 3 atomic isotopes'),
('Argon', 'Ar', '18', '39.0983', 'Noble gas', 'Gas', 'abundant element in our vicinity', 'cheapest and most frequently used noble gas', 'comes into operation, when an inert atmosphere is needed', 'It is nearly transparent for X-rays', 'not often used, as it is quite expensive and very toxic', 'it is an important ingredient in many valuable gemstones'),
('Potassium', 'K', '19', '39.948', 'Alkali metal', 'Solid', 'explosively reacts with water', 'several natural minerals contain it', 'It is responsible for the largest part of the normal radioactive exposure.', 'This element gives purple color when heated', 'Gas lasers are made with the help of this', 'used in semiconductor manufacturing for plasma etching, MEMs fabrication, and flat panel display production'),
('Calcium', 'Ca', '20', '40.078', 'Alkaline earth metal', 'Solid', 'grey metal', 'very important for humans and animals', 'slowly reacts with air and fiercely reacts with water', 'used extensively used in air conditioners and refrigerators', 'It is used in Flash lamps', 'It is most expensive and most dense of all the gases'),
('Scandium', 'Sc', '21', '44.9559', 'Transition metal', 'Solid', 'soft and silvery', 'first transition metal and the first rare earth element', 'It is used in high-quality, light alloys', 'shares similar properties to that of lanthanum.', 'was first detected as an emission from the radioactive decay of radium.', 'It can create exotic compounds with fluorine in laboratories'),
('Titanium', 'Ti', '22', '47.867', 'Transition metal', 'Solid', 'light, but very strong metal', 'Is is quite frequent, but hard to extract', 'It is used a lot for technical components and steels', 'It is chemically inert gas and non-toxic in nature', 'forms an unstable hydrate.', 'This element gives purple color when heated'),
('Vanadium', 'V', '23', '50.9415', 'Transition metal', 'Solid', 'soft, malleable metal', 'when exposed to air, forms a hard, protective oxide layer', 'It is mainly used in steel alloys', 'It is found in both free and in the combined state', 'It produces a bluish purple colour when electrified', 'It is commonly called limestone'),
('Chromium', 'Cr', '24', '51.9961', 'Transition metal', 'Solid', 'very hard and shiny silvery metal', 'used for plating for optical reasons and corrosion protection', 'added to steel, to make it stainless.', 'It does not react with oxygen in the air', 'Its common name is “quicksilver”', 'The metal is mainly used to manufacture jewelry, glass and different parts in electronics items'),
('Manganese', 'Mn', '25', '54.938', 'Transition metal', 'Solid', 'very common metal and is often used in alloys', 'It can be found in nature in large quantities in many minerals.', 'Its probably most famous compound is the strong oxidizing agent potassium permanganate', 'It does not react with oxygen in the air', 'used extensively used in air conditioners and refrigerators', 'Very high surface tension'),
('Iron', 'Fe', '26', '55.845', 'Transition metal', 'Solid', 'Commonly it is alloyed together with carbon and other elements, to become steel', 'essential for mammals and makes our blood red', 'mostly found in ores', 'It is found in both free and in the combined state', 'It produces a bluish purple colour when electrified', 'It is commonly called fool\'s gold'),
('Cobalt', 'Co', '27', '58.6934', 'Transition metal', 'Solid', 'ferromagnetic, ductile metal, which is very similar to iron', ' It is used for magnets and for many different alloys', 'part of the vitamin B12 and therefore is needed in small amounts in our food.', 'has an ability to make long chains and rings', 'It is comonly called lye', 'used as a catalyst in organic chemistry'),
('Nickel', 'Ni', '28', '58.9332', 'Transition metal', 'Solid', 'together with iron, forms the inner core of the Earth', 'quite inert metal, which often is used for plating', 'the most stable isotope', 'It is chemically inert gas and non-toxic in nature', 'It can create exotic compounds with fluorine in laboratories', 'Gas lasers are made with the help of this.'),
('Copper', 'Cu', '29', '63.546', 'Transition metal', 'Solid', 'It is known since ancient times and was the first metal used by humans', 'In an alloy together with zinc, it forms brass', 'has a very high electrical conductivity, so it is used for most electrical lines', 'part of the vitamin B12 and therefore is needed in small amounts in our food.', 'Commonly it is alloyed together with carbon and other elements, to become steel', 'essential for mammals and makes our blood red'),
('Zinc', 'Zn', '30', '65.39', 'Transition metal', 'Solid', 'bluish silvery, brittle and hard metal', 'in air quickly forms an enduring protective layer. Therefore it is used a lot as corrosion prevention', 'essential trace element, which above all is needed for the metabolism and which occurs in many foods.', 'It is the lightest solid metal.', 'takes an active part in many reactions with organic and inorganic reactants. It reacts with oxygen to form monoxide and peroxide.', 'is a chemical element that occurs first in the alkalis of the periodic table.'),
('Gallium', 'Ga', '31', '69.723', 'Post-transition metal', 'Solid', 'soft, silvery metal, which is increasingly used in high tech industry', 'It is relatively safe to handle, but eye contact and longer skin contact should be avoided.', 'It is stable in air and water; but it reacts with and dissolves in acids and alkali', 'superheavy element on the periodic table, which does not occur naturally', 'chemical element that occurs first in the alkalis of the periodic table.', 'catenation and multiple bond formation are common properties'),
('Germanium', 'Ge', '32', '72.64', 'Metalloid', 'Solid', 'shiny silvery metalloid and a semiconductor', 'corrosion-resistant, very brittle and slightly toxic', 'It has a diamondlike crystalline structure and it is similar in chemical and physical properties to silicon', 'It is used in the manufacture of ammonia, to produce nitric acid and subsequently used as a fertilizer', 'Around eighty percent of the Earth’s atmosphere comprises of this.', 'It is used in the production and manufacturing of glass and stone products, and in mining'),
('Arsenic', 'As', '33', '74.9216', 'Metalloid', 'Solid', 'appears in three allotropic forms: yellow, black and grey; the stable form is a silver-gray', 'The non metallic form is less reactive but will dissolve when heated with strong oxidizing acids and alkalis.', 'The metallic form is brittle, tharnishes and when heated it rapidly oxidizes to give a garlic odour', 'in the air combines with water particles and get dissolved into water or soils', 'used to manufacture steel and also used in civil engineering like reinforced concrete, girders etc.', 'catalysts are used in the Haber process for producing ammonia'),
('Selenium', 'Se', '34', '78.96', 'Nonmetal', 'Solid', 'Chemically it resembles sulfur, but is less reactive than this', 'Every life form on earth needs it in small amounts for different proteins and amino acids', 'appears in a number of allotropic forms: the most popular are a red amorphous powder, a red crystalline material, and a gray crystalline metal like form', 'burns with a bright, white flame at a temperature of more than 3000 K', 'strong metallic lustre and in colour is very analogous to silver', 'once was used as flashlight for photography and is still used in underwater torches'),
('Bromine', 'Br', '35', '79.904', 'Halogen', 'Liquid', 'At ambient temperature it is a brownish-red liquid', 'It has a similarly colored vapor with an offensive and suffocating odor', 'It is the only nonmetallic element that is liquid under ordinary conditions', 'a very reactive gas, is the most abundant element on Earth', 'It is produced by plants doing photosynthesis', 't is part of very many natural compounds, in minerals as in organic material and of course in water, H2O'),
('Krypton', 'Kr', '36', '83.8', 'Noble gas', 'Gas', 'It has some use in laser technology and in lamps, where it makes a bright, white light', 'It is characterised by its brilliant green and orange spectral lines', 'Under normal conditions it is colourless, odourless, fairly expensive gas', 'relatively inert, hard, medium grey metal', 'was used for optical lenses in former times', 'The most important use of this is the ammonia synthesis'),
('Rubidium', 'Rb', '37', '85.4678', 'Alkali metal', 'Solid', 'soft, silvery-white metallic element of the alkali metals group (Group 1)', 't is one of the most electropositive and alkaline elements', 'Its flame is yellowish-violet.', 'essential trace element, which above all is needed for the metabolism and which occurs in many foods.', 'has an ability to make long chains and rings', 'Gas lasers are made with the help of this.'),
('Strontium', 'Sr', '38', '87.62', 'Alkaline earth metal', 'Solid', 'very similar to calcium, but it is more heavy and reactive', 'salts are used to make red fireworks', 'notorious for the radioactive 90Sr, which is produced in nuclear power plants as well as in atomic explosions like that in Chernobyl and from atomic bomb', 'The metallic form is brittle, tharnishes and when heated it rapidly oxidizes to give a garlic odour', 'It produces a bluish purple colour when electrified', 'It does not react with oxygen in the air'),
('Yttrium', 'Y', '39', '88.9059', 'Transition metal', 'Solid', 'soft and reactive metal', 'YAG, yttrium aluminium garnet, is widely used as a host material in lasers', 'Pure yttrium easily forms crystals', 'It is used in the manufacture of ammonia, to produce nitric acid and subsequently used as a fertilizer', 'Commonly it is alloyed together with carbon and other elements, to become steel', 'It is used in the production and manufacturing of glass and stone products, and in mining'),
('Zirconium', 'Zr', '40', '91.224', 'Transition metal', 'Solid', 'hard, silvery grey metal', 'quite reactive, but forms a protective oxide layer in air, which makes it corrosion-resistant', 'it is used for special alloys', 'burns with a bright, white flame at a temperature of more than 3000 K', 'It is produced by plants doing photosynthesis', 'once was used as flashlight for photography and is still used in underwater torches'),
('Niobium', 'Nb', '41', '92.9064', 'Transition metal', 'Solid', 'rare, soft, grey metal, which, when exposed to air, quickly forms a protective oxide layer', 'additive to superalloys, which have to withstand very high temperatures', 'mint metal for special coinages, because it can be anodized to form a colored oxide layer. The thickness of the oxide layer determines its color.', 'It is the only nonmetallic element that is liquid under ordinary conditions', 'strong metallic lustre and in colour is very analogous to silver', 'It produces a bluish purple colour when electrified'),
('Molybdenum', 'Mo', '42', '95.94', 'Transition metal', 'Solid', 'one of the most heavy elements of those essential to life', 'enzyme nitrogenase with molybdenum in its active center, which allows some bacteria to process nitrogen from the air.', 'In elemental form, the hard, heavy and ductile metal is used for many special technical applications, like for the tempering of steel.', 'It is the only nonmetallic element that is liquid under ordinary conditions', 'essential trace element, which above all is needed for the metabolism and which occurs in many foods.', 't is part of very many natural compounds, in minerals as in organic material and of course in water, H2O'),
('Technetium', 'Tc', '43', '98', 'Transition metal', 'Solid', 'first element without stable isotopes', 'most important application in medicine, where the isomer 99mTc is a main substance for radio diagnosis. This is made synthetically.', 'It is a silvery, hard, relatively noble metal with attributes similar to rhenium.', 'burns with a bright, white flame at a temperature of more than 3000 K', 'chemical element that occurs first in the alkalis of the periodic table.', 'in the air combines with water particles and get dissolved into water or soils'),
('Ruthenium', 'Ru', '44', '101.07', 'Transition metal', 'Solid', 'first of the platinum group metals', 'crystallizes hexagonal', 'hard and brittle and is commonly used in alloys and as a catalyst.', 'It does not react with oxygen in the air', 'It is the only nonmetallic element that is liquid under ordinary conditions', 'soft, malleable metal'),
('Rhodium', 'Rh', '45', '102.9055', 'Transition metal', 'Solid', 'rarest and most valuable stable metal on earth.', 'It is needed in many chemical applications as a catalyst, like for example in the industrial production of acetic acid.', 'In catalytic converters, it reduces the amount of toxic material that arises from the combustion', 'additive to superalloys, which have to withstand very high temperatures', 'most important application in medicine, where the isomer 99mTc is a main substance for radio diagnosis. This is made synthetically.', 'very similar to calcium, but it is more heavy and reactive'),
('Palladium', 'Pd', '46', '106.42', 'Transition metal', 'Solid', 'very similar to platinum and like this is often used for catalysts and for jewellery', 'more reactive than platinum and cheaper than this', 'Palladium can very well absorb, store and then release hydrogen.', 'corrosion-resistant, very brittle and slightly toxic', 'it is used for special alloys', 'The metallic form is brittle, tharnishes and when heated it rapidly oxidizes to give a garlic odour'),
('Silver', 'Ag', '47', '107.8682', 'Transition metal', 'Solid', 'most abundant noble metal and is widely used for jewellery, coins and for technical applications', 'highest electric and thermic conductivity and the whitest color of all metals', 'Silver compounds, like silver bromide, are used for photographic films, as some of them are very photosensitive', 'most important application in medicine, where the isomer 99mTc is a main substance for radio diagnosis. This is made synthetically.', 'essential trace element, which above all is needed for the metabolism and which occurs in many foods.', 'It produces a bluish purple colour when electrified'),
('Cadmium', 'Cd', '48', '112.411', 'Transition metal', 'Solid', 'bluish silvery, soft, ductile metal, which is a by-product in the production of zinc and other metals', 'It has a bad reputation, because it is in virtually every form very toxic and harmful to the environment.', 'An important application are nickel-cadmium batteries, which, when defect, have to be disposed properly.', 'Under normal conditions it is colourless, odourless, fairly expensive gas', 'It is the only nonmetallic element that is liquid under ordinary conditions', 'once was used as flashlight for photography and is still used in underwater torches'),
('Indium', 'In', '49', '114.818', 'Post-transition metal', 'Solid', 'rare metal with a low melting point', 'very soft and can be cut with a knife', 'Indium tin oxide is transparent, but has a good electrical conductivity.', 'mint metal for special coinages, because it can be anodized to form a colored oxide layer. The thickness of the oxide layer determines its color.', '', 'It is produced by plants doing photosynthesis'),
('Tin', 'Sn', '50', '118.71', 'Post-transition metal', 'Solid', 'very common metal. It is soft and has a low melting point,', 'used since ancient times. Bronze is usually an alloy of copper and tin', 'common β-tin can transform into powdery α-tin at low temperatures (below 13°C, 56°F). This is known as tin pest, which destroys the affected item.', '', 'It is used in the manufacture of ammonia, to produce nitric acid and subsequently used as a fertilizer', 'superheavy element on the periodic table, which does not occur naturally'),
('Antimony', 'Sb', '51', '121.76', 'Metalloid', 'Solid', 'metalloid (or semi metal), which is rather metal than nonmetal', ' it is quite toxic and has effects similar to arsenic, but weaker.', 'important for semiconductors, but has been used for a long time as additive in alloys like bronze and in cosmetics', 'hard and brittle and is commonly used in alloys and as a catalyst.', 'It is the only nonmetallic element that is liquid under ordinary conditions', 'strong metallic lustre and in colour is very analogous to silver'),
('Tellurium', 'Te', '52', '126.9045', 'Metalloid', 'Solid', 'chemically similar to selenium', '. It can form nice crystals and sometimes natively occurs in nature, however it is very rare.', 'element that most easily forms compounds with gold,', 'Silver compounds, like silver bromide, are used for photographic films, as some of them are very photosensitive', 'additive to superalloys, which have to withstand very high temperatures', 'most important application in medicine, where the isomer 99mTc is a main substance for radio diagnosis. This is made synthetically.');
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
